### ISSUE TITLE
The closed event is triggered twice when slide down quickly

### ISSUE THREAD

**Issue by Gitsifu** [vaban-ru/vue-bottom-sheet-vue2#1]

**Comment by Gitsifu** [comment]
I feel like that's what's causing the problem

https://github.com/Gitsifu/vue-bottom-sheet-vue2/issues/1

**Comment by vaban-ru** [comment]
> I feel like that's what's causing the problem
> 
> [Gitsifu#1](https://github.com/Gitsifu/vue-bottom-sheet-vue2/issues/1)

Hey! You can send PR if you want

**Comment by Gitsifu** [comment]
> > I feel like that's what's causing the problem
> > [Gitsifu#1](https://github.com/Gitsifu/vue-bottom-sheet-vue2/issues/1)
> 
> Hey! You can send PR if you want

OK! No problem

**Comment by Gitsifu** [comment]
> > I feel like that's what's causing the problem
> > [Gitsifu#1](https://github.com/Gitsifu/vue-bottom-sheet-vue2/issues/1)
> 
> Hey! You can send PR if you want

Since the company needed it urgently, I created a new npm package

**Comment by vaban-ru** [comment]
> > > I feel like that's what's causing the problem
> > > [Gitsifu#1](https://github.com/Gitsifu/vue-bottom-sheet-vue2/issues/1)
> > 
> > 
> > Hey! You can send PR if you want
> 
> Since the company needed it urgently, I created a new npm package

If you send me PR, i can update npm version in 1 minute

**Comment by vaban-ru** [comment]
> > > I feel like that's what's causing the problem
> > > [Gitsifu#1](https://github.com/Gitsifu/vue-bottom-sheet-vue2/issues/1)
> > 
> > 
> > Hey! You can send PR if you want
> 
> Since the company needed it urgently, I created a new npm package

Released new 0.0.7 version

**Comment by vaban-ru** [comment]
[#2 ](https://github.com/vaban-ru/vue-bottom-sheet-vue2/pull/2)

**Comment by Gitsifu** [comment]
When the fast slide, the close event was triggered twice this issue has not been dealt with. Please look again
