### ISSUE TITLE
"window is not defined" error when using SSR

### ISSUE THREAD

**Issue by symos** [vaban-ru/vue-bottom-sheet-vue2#5]
We are trying to add some bottom sheets to our project which uses SSR.
We've installed the package but it throws "ReferenceError: window is not defined" when running on the server.

If we comment out everything in the file "vue-bottom-sheet-vue2.ssr.js" then it works, it gets rendered client side and the bottom sheets work as expected.

However, I'm not sure how the SSR version is supposed to work, since there is indeed no window object defined on the server. Is there any way to define it? And if so, what would this accomplish?

**Comment by vaban-ru** [comment]
> We are trying to add some bottom sheets to our project which uses SSR. We've installed the package but it throws "ReferenceError: window is not defined" when running on the server.
> 
> If we comment out everything in the file "vue-bottom-sheet-vue2.ssr.js" then it works, it gets rendered client side and the bottom sheets work as expected.
> 
> However, I'm not sure how the SSR version is supposed to work, since there is indeed no window object defined on the server. Is there any way to define it? And if so, what would this accomplish?

Hey! You are using Nuxt?

**Comment by symos** [comment]
Thanks for the quick response! 

We are using the old version of VueStorefront (https://github.com/vuestorefront/vue-storefront-1). It doesn't use Nuxt as far as I know and can see in the code.

**Comment by vaban-ru** [comment]
> Thanks for the quick response!
> 
> We are using the old version of VueStorefront (https://github.com/vuestorefront/vue-storefront-1). It doesn't use Nuxt as far as I know and can see in the code.

Unfortunately, I've never used it, so I haven't tested the plugin there. I think that you somehow need to exclude the plugin from server-side rendering, for example in Nuxt a special tag was used for this <client-only>, but how it works in Vue Storefront i dont know((

**Comment by symos** [comment]
We use the "vue-no-ssr" package to exclude things from server side rendering. This is what we will do. 
I was just wondering if there is a way to make it work without this since you include a separate SSR file. But probably not.

OK, thank you, we will exclude the plugin from SSR.

**//edit:** 

Just as a note for anyone reading this in the future, no-ssr didn't work because the error is thrown on import, before the plugin is used.

The solution that worked was to dynamically import the package, so instead of doing this:
_import VueBottomSheetVue2 from '@webzlodimir/vue-bottom-sheet-vue2'_

we now do this:
_const VueBottomSheetVue2 = () => import('@webzlodimir/vue-bottom-sheet-vue2');_

Instead of an error, this throws a warning on the server and then imports the plugin when window becomes available.

Background info on dynamic imports:
https://vuedose.tips/dynamic-imports-in-vue-js-for-better-performance
